### PR TITLE
Improve Jarvis API class to be more "python like"

### PR DESCRIPTION
**Pull request by QuentinCG**
Use word "self" as defined in python class.
This could for example allow to have more than one instance of Jarvis() class.

### CODE REVIEW

**Comment by QuentinCG** [comment]
This is a minor "improvement" (it is more to "make the code prettier" than something really useful...)

**Comment by alexylem** [comment]
Thanks a lot!

**Comment by QuentinCG** [comment]
Outch..... I'm quite confused...
I did so many changes and learnings on those plugins this week that I failed on this fix... (it is indeed not working): I patched it too quickly...

My bad...

**Comment by alexylem** [comment]
No worries it has been quickly recovered 😄  
It's my fault I'm supposed to test all pull requests before merging
Don't hesitate to continue contributing, it's thanks to you guys Jarvis is evolving so fast!!

**Pull request merged**
